# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: engine.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'engine.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0c\x65ngine.proto\x12\x06\x65ngine\"N\n\x10\x42\x65stMovesRequest\x12\x0f\n\x07game_id\x18\x01 \x01(\t\x12\x13\n\x0b\x62oard_state\x18\x02 \x01(\t\x12\x14\n\x0c\x61\x63tive_color\x18\x03 \x01(\t\"\x83\x01\n\rSuggestedMove\x12\x16\n\x0epiece_position\x18\x01 \x01(\t\x12\x17\n\x0ftarget_position\x18\x02 \x01(\t\x12\x11\n\tmove_type\x18\x03 \x01(\t\x12\x0c\n\x04rank\x18\x04 \x01(\x05\x12\x11\n\treasoning\x18\x05 \x01(\t\x12\r\n\x05score\x18\x06 \x01(\x05\"f\n\x11\x42\x65stMovesResponse\x12$\n\x05moves\x18\x01 \x03(\x0b\x32\x15.engine.SuggestedMove\x12\x14\n\x0c\x61\x63tive_color\x18\x02 \x01(\t\x12\x15\n\rerror_message\x18\x03 \x01(\t2R\n\x0b\x43hessEngine\x12\x43\n\x0cGetBestMoves\x12\x18.engine.BestMovesRequest\x1a\x19.engine.BestMovesResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'engine_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_BESTMOVESREQUEST']._serialized_start=24
  _globals['_BESTMOVESREQUEST']._serialized_end=102
  _globals['_SUGGESTEDMOVE']._serialized_start=105
  _globals['_SUGGESTEDMOVE']._serialized_end=236
  _globals['_BESTMOVESRESPONSE']._serialized_start=238
  _globals['_BESTMOVESRESPONSE']._serialized_end=340
  _globals['_CHESSENGINE']._serialized_start=342
  _globals['_CHESSENGINE']._serialized_end=424
# @@protoc_insertion_point(module_scope)
